### ISSUE TITLE
BloodRequirement seems to let DRK use abilities with insufficient Blood Gauge

### ISSUE THREAD

**Issue by omor1** [IAmPythagoras/FFXIV-Combat-Simulator#12]
The definition for `BloodRequirement`, reproduced below, seems from my understanding of the code to let players use Bloodspiller, Quietus, and Living Shadow even when `Player.Blood < 50`, since it always return `(True, -1)`.

```python
def BloodRequirement(Player, Spell):
    if Player.DeliriumStacks > 0 and (Spell.id == Bloodspiller.id or Spell.id == Quietus.id):
        Spell.BloodCost = 0
        Player.DeliriumStacks -= 1
        return True, -1
    elif Player.Blood >= 50:
        Player.Blood -= 50
        return True, -1
    return True, -1
```

I think that `TBNRequirement` and `EdgeShadowRequirement` are similar in that they return `(True, -1)` even when you have insufficient mana.

**Comment by IAmPythagoras** [comment]
oh you are right. I must have changed it some time ago when testing some stuff. Ill change it back to what its supposed to be.

**Comment by omor1** [comment]
Don't forget `EdgeShadowRequirement` and `TBNRequirement` too 😀.
