### ISSUE TITLE
Specify stats/actions/etc via json or config file

### ISSUE THREAD

**Issue by nonowazu** [IAmPythagoras/FFXIV-Combat-Simulator#17]
Piggybacking off #15 a little bit, I'd like to suggest a json file for submitting stats and actions for a team. I don't have a defined format in my head, but maybe something like:

```json5
{
    "BLM": { // friendly name
        "job": "Black Mage",
        "stats": {
            "MainStat": 2945, // etc
        },
        "opener": [
            "SharpCast", // etc
        ]
     },
    // other jobs to sim at the same time here
}
```

I think this would remove 90% of the editing requirements for `main.py`, which would be helpful – and it could be rolled into cli work; perhaps something like `ffxivcombatsim simulate --party /path/to/party.json`?

**Comment by IAmPythagoras** [comment]
In theory this could already be done with how I implemented the saving functions of fights. My reasoning was that it would still be easier to just write in code since editing a json file in a text editor would imo be more of a pain. I wanted to at some point add a GUI that would make the editing of such JSON file way more easy and user friendly, but I do not know how to code GUIs currently.

I am not a fan of the coding UI I came up with, but its the best way I could think of where people wouldn't directly modify a JSON file lol. 

But yeah, as I we could simply use the already in place model I made for that (its quite similar to what you have, except each action have other fields to them). You can try yourself by saving one of the fights and looking at the JSON file created.

**Comment by nonowazu** [comment]
I'm fine with that as a format (though I can tell that file is heavily sourced from fflogs, haha) - as long as someone can specify something to go through the simulation to save some time. In terms of writing in code, I think the "library" approach will let people programmatically work with that.

**Comment by periodically-au** [comment]
A side benefit of moving to a JSON style config is it become easy to integrate other stuff like etro.gg into the tool, cuz they have an api that gets you a `Dict` object from just a url. This can be mixed in when the CLI stuff comes alive to some extent, and might even off-load some ongoing work. I've moved the personal sim I have to using etro's values for `damage_per_100_potency` for this reason so I can just leverage their work.

I'm very slow to do anything like contribute, but here's a pseudo-snippet I use to get the etro stats from a given id or url

```
# Installed versions I use
# coreapi==2.3.3
# coreapi-cli==1.0.9
import coreapi

def get_gearset_data(set_id: str) -> Dict:
    """Gets the gearset data (stats) via an id. Allows url too (handles it for free)"""
    # Handles urls by checking for webpage name and splitting
    cleaned_set_id = set_id.split("/")[-1] if "etro.gg/gearset" in set_id else set_id
    client = coreapi.Client()
    data = client .action(
        client.get("https://etro.gg/api/docs/"),
        ["gearsets", "read"],
        params={
            "id": cleaned_set_id,
        },
    )
   
     # cleanup logic
     stats = {
        params["name"]: params["value"]
        if "units" not in params or params["units"] != "%"
        else (round(params["value"] / 100.0, 4))
        for params in data["totalParams"]
     }
     
     return {
          "id": data["id"],
          "url": f"https://etro.gg/gearset/{self._etro_data['id']}",
          "jobAbbrev":  data["jobAbbrev"],
          # Cleans up job values
          **stats,
      }
```

Output looks like this, for an example
```
 {'Average Item Level': 622,
           'CRT': 2454,
           'Critical Hit Multiplier': 1.616,
           'Critical Hit Rate': 0.266,
           'DEF': 4674,
           'DET': 1733,
           'DH': 988,
           'Damage (Expected)': 2337.29,
           'Defense Mitigation': 0.36,
           'Determination Multiplier': 1.098,
           'Direct Critical Multiplier': 2.02,
           'Direct Critical Rate': 0.04522,
           'Direct Hit Rate': 0.17,
           'Food Values': OrderedDict([('3', 118), ('27', 97), ('45', 58)]),
           'GCD': 2.42,
           'HP': 98519,
           'Materia Totals': OrderedDict([('33918', 7),
                                          ('33919', 2),
                                          ('33928', 1),
                                          ('33931', 14),
                                          ('33932', 4),
                                          ('33941', 6)]),
           'Materia Values': OrderedDict([('22', 588),
                                          ('27', 168),
                                          ('45', 228)]),
           'Medicine Values': None,
           'SKS': 851,
           'STR': 2786,
           'STR Multiplier': 10.58,
           'Skill Speed Multiplier': 1.03,
           'TEN': 495,
           'Tenacity Mitigation': 0.005,
           'Tenacity Multiplier': 1.005,
           'VIT': 3116,
           'Weapon DMG Multiplier': 1.65,
           'Weapon Damage': 126,
           'id': '9380f273-6fe0-4267-915c-86e68cdb38b6',
           'jobAbbrev': 'GNB',
           'url': 'https://etro.gg/gearset/9380f273-6fe0-4267-915c-86e68cdb38b6'}
```

@IAmPythagoras feel free to reach out if you want more source code on the etro stuff.
@nonowazu love the nice ideas for this repo, an editable json would be amazing, I just feel like the etro option will help a lot of people who just look at balance recommended bis jumpstart their experience with this repo. Etro based stuff can be a nice initial step when also looking at the CLI methods.

**Comment by nonowazu** [comment]
For excessive json usage here, it might be worth bringing in a dependency on [pydantic](https://pydantic-docs.helpmanual.io/), since that allows you to force validation and do transforms and etc.

**Comment by IAmPythagoras** [comment]
Hey! I just saw those answer but ill have a look more in depth at it tomorrow. Thanks again for the ideas \o/
