### ISSUE TITLE
Supported python version(s)?

### ISSUE THREAD

**Issue by nonowazu** [IAmPythagoras/FFXIV-Combat-Simulator#8]
I personally use python 3.10, which (if you do the same) would mean some better typing support and also supports [structural pattern matching](https://peps.python.org/pep-0622/) (which you could pretty immediately use as a case statement in some of the code I've glanced through to clean up some things).

I'd suggest putting the supported version in a `.python-version` file so tools like `pyenv` can take immediate advantage of it.

**Comment by IAmPythagoras** [comment]
I believe python 3.10 works with it anyway. My laptop runs python 3.10 and my home computer runs python 3.9. When I realized they both ran different version I went on python 3.9 (for no reason in particular), but the code was running smoothly on python 3.10 too.

**Comment by IAmPythagoras** [comment]
I will also look into adding a .python-version file
